INSERT INTO DIRECTOR VALUES('D1','FERNANDO','FLORES','CAMACHO','MAESTRIA');
INSERT INTO AUTOR VALUES ('A1','MEXICANO','LEONARDO','CARRILLO','CONTRERAS');
INSERT INTO MATERIAL VALUES('M1','ROBOTICA ESTRATEGIA DIDACTICA','EDIFICIO A','T001','TESIS');
INSERT INTO PERTENECE VALUES('A1','M1');
INSERT INTO TESIS VALUES('M1','D1','T1','FISICA',TO_DATE('01/02/2020','dd/mm/yyyy'));
INSERT INTO EJEMPLAR VALUES (1,'M1','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (2,'M1','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (3,'M1','NO SALE');

INSERT INTO DIRECTOR VALUES('D2','HERNAN','LARRALDE','RIDAURA','DOCTORADO');
INSERT INTO AUTOR VALUES ('A2','MEXICANO','LUISANA','CLAUDIO','PACHECANO');
INSERT INTO MATERIAL VALUES('M2','AGLOMERACIONES DE NEGOCOS','EDIFICIO A','T002','TESIS');
INSERT INTO PERTENECE VALUES('A2','M2');
INSERT INTO TESIS VALUES('M2','D2','T2','FISICA',TO_DATE('11/06/2020','dd/mm/yyyy'));
INSERT INTO EJEMPLAR VALUES (1,'M2','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (2,'M2','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (3,'M2','NO SALE');

INSERT INTO DIRECTOR VALUES('D3','JESSICA','ROSAS','GUTIERREZ','MAESTRIA');
INSERT INTO AUTOR VALUES ('A3','MEXICANO','DIEGO','CASTRO','MORALES');
INSERT INTO MATERIAL VALUES('M3','PLUS ULTRA, TERRA FIRMA','EDIFICIO A','T003','TESIS');
INSERT INTO PERTENECE VALUES('A3','M3');
INSERT INTO TESIS VALUES('M3','D3','T3','ARTES',TO_DATE('13/05/2005','dd/mm/yyyy'));
INSERT INTO EJEMPLAR VALUES (1,'M3','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (2,'M3','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (3,'M3','NO SALE');

INSERT INTO AUTOR VALUES('A4','ESTADOS UNIDOS','ROLAND','EDWIN','LARSON');
INSERT INTO MATERIAL VALUES('M4','CALCULO','EDIFICIO A','B001','LIBRO');
INSERT INTO PERTENECE VALUES ('A4','M4');
INSERT INTO LIBRO VALUES('M4',1,'9788436820','MATEMATICAS','DECIMA EDICION');
INSERT INTO EJEMPLAR VALUES (1,'M4','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (2,'M4','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (3,'M4','NO SALE');

INSERT INTO AUTOR VALUES('A5','REINO UNIDO','BHAT','RAMDAS',NULL);
INSERT INTO MATERIAL VALUES('M5','MODERN PROBABILITY THEORY','EDIFICIO A','B002','LIBRO');
INSERT INTO PERTENECE VALUES ('A5','M5');
INSERT INTO LIBRO VALUES('M5',2,'9780852260','MATEMATICAS','SEGUNDA EDICION');
INSERT INTO EJEMPLAR VALUES (1,'M5','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (2,'M5','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (3,'M5','NO SALE');

INSERT INTO AUTOR VALUES('A6','FRANCIA','ANTONIE','SAINT-EXUPERY',NULL);
INSERT INTO MATERIAL VALUES('M6','EL PRINCIPITO','EDIFICIO A','B003','LIBRO');
INSERT INTO PERTENECE VALUES ('A6','M6');
INSERT INTO LIBRO VALUES('M6',3,'9788498386','CUENTOS','PRIMERA EDICION');
INSERT INTO EJEMPLAR VALUES (1,'M6','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (2,'M6','DISPONIBLE');
INSERT INTO EJEMPLAR VALUES (3,'M6','NO SALE');

/*
SELECT COUNT(*) FROM MATERIAL;
SELECT COUNT(*) FROM AUTOR;
SELECT COUNT(*) FROM PERTENECE;
SELECT COUNT( *) FROM LIBRO;
SELECT COUNT (*) FROM TESIS;
SELECT COUNT(*) FROM DIRECTOR;
SELECT COUNT(*) FROM EJEMPLAR;
*/
--select table_name from user_tables;

INSERT INTO TIPOLECTOR VALUES('ESTUDIANTE',3,8,1);
INSERT INTO TIPOLECTOR VALUES('PROFESOR',5,15,2);
INSERT INTO TIPOLECTOR VALUES('INVESTIGADOR',10,30,3);
--select * FROM tipolector;

INSERT INTO LECTOR 
VALUES('L1','ANTONIO','GARCIA','VASQUEZ','MIGUEL HIDALGO',
'POLANCO',327,SYSDATE,11550,NULL,TO_DATE('09/05/2022','dd/mm/yyyy'),'ESTUDIANTE');

INSERT INTO LECTOR 
VALUES('L2','ROSA','PENA','DELGADO','XOCHIMILCO',
'JARDINES DEL SUR',74,SYSDATE,16050,NULL,TO_DATE('09/05/2022','dd/mm/yyyy'),'ESTUDIANTE');

INSERT INTO LECTOR 
VALUES('L3','IRMA','MORENO','CASTILLO','COYOACAN',
'SANTO DOMINGO',35,SYSDATE,04369,NULL,TO_DATE('09/05/2022','dd/mm/yyyy'),'PROFESOR');

INSERT INTO LECTOR 
VALUES('L4','LUIS','CASTRO','RAMIREZ','COYOACAN',
'COPILCO UNIVERSIDAD',29,SYSDATE,04360,NULL,TO_DATE('09/05/2022','dd/mm/yyyy'),'PROFESOR');

INSERT INTO LECTOR 
VALUES('L5','MARTIN','ORTEGA','SANTIAGO','COYOACAN',
'COPILCO UNIVERSIDAD',17,SYSDATE,04361,NULL,TO_DATE('09/05/2022','dd/mm/yyyy'),'INVESTIGADOR');

--select * from lector;



ALTER TABLE lector DROP CONSTRAINT UNIQUECP;
ALTER TABLE lector ADD calle VARCHAR2(30);
UPDATE lector SET calle='ECONOMIA' WHERE  idlector='L5';
UPDATE lector SET calle='CERRADAS TEXALPA' WHERE idlector='L3';
UPDATE lector SET calle='ANATOLE FRANCE' WHERE idlector='L1';
UPDATE lector SET calle='SACATECAS' WHERE idlector='L2';
UPDATE lector SET calle='CERRO SABINO 3-17' WHERE idlector='L4';

--select * from lector;

ALTER TABLE prestamo DROP COLUMN idprestamo;
ALTER TABLE  lector MODIFY calle VARCHAR2(30) NOT NULL;
--
