--********************************TRIGGERS**********************************
--TRIGGER PARA CAMBIAR EL ESTATUS AL INSERTAR EN PRESTAMO
CREATE OR REPLACE TRIGGER TR_ESTATUS_PRESTAMO
BEFORE INSERT ON PRESTAMO
FOR EACH ROW
DECLARE
V_ESTATUS EJEMPLAR.ESTATUS%TYPE;
BEGIN    
    V_ESTATUS := FT_PRESTAMODISP(:NEW.IDMATERIAL);
    IF(V_ESTATUS='DISPONIBLE') THEN
    	UPDATE EJEMPLAR SET ESTATUS='PRESTAMO'
    	WHERE IDMATERIAL = :NEW.IDMATERIAL;
    ELSE
    	IF (V_ESTATUS='NO SALE') THEN
    		DBMS_OUTPUT.PUT_LINE('EL MATERIAL NO PUEDE SALIR DE LA BIBLIOTECA');
    	ELSE
    		IF (V_ESTATUS='MANTENIMIENTO') THEN
    			DBMS_OUTPUT.PUT_LINE('EL MATERIAL SE ENCUENTRA EN MANTENIMIENTO');
    		ELSE
    			IF (V_ESTATUS='PRESTAMO') THEN
    				DBMS_OUTPUT.PUT_LINE('EL MATERIAL YA ENCUENTRA EN PRESTAMO');3
    			END IF;
    		END IF;
    	END IF;
    END IF;
END;
/