--*********************************VIEWS************************************
--VIEW DE AUTORES
CREATE OR REPLACE VIEW VW_AUTOR AS
	SELECT IDAUTOR,NACIONALIDAD,NOMBREA,APELLIDOPA,APELLIDOMA
	FROM AUTOR;

--VIEW DE DIRECTORES
CREATE OR REPLACE VIEW VW_DIRECTOR AS
	SELECT IDDIRECTOR,NOMBRED,APELLIDOPD,APELLIDOMD,GRADO 
    FROM DIRECTOR;

--VIEW DE EJEMPLARES
CREATE OR REPLACE VIEW VW_EJEMPLAR AS
	SELECT NOEJEMPLAR,IDMATERIAL,ESTATUS
	FROM EJEMPLAR;

--VIEW DE LECTORES
CREATE OR REPLACE VIEW VW_LECTOR AS
	SELECT IDLECTOR,NOMBREL,APELLIDOPL,APELLIDOML,DELEGACION,
	COLONIA,NUMERO,FECHAALTA,CP,ADEUDO,FECHAVIGENCIA,TIPO
	FROM LECTOR

--VIEW DE LIBROS
CREATE OR REPLACE VIEW VW_LIBRO AS
	SELECT IDMATERIAL,NOADQUISICION,ISBN,TEMA,EDICION
	FROM LIBRO

--VIEW DE MATERIALES
CREATE OR REPLACE VIEW VW_MATERIAL AS
	SELECT IDMATERIAL,TITULO,UBICACION,COLOCACION,TIPOMATERIAL 
	FROM MATERIAL

--VIEW DE PERTENECE
CREATE OR REPLACE VIEW VW_PERTENECE AS
	SELECT IDAUTOR,IDMATERIAL
    FROM PERTENECE

--VIEW DE PRESTAMOS
CREATE OR REPLACE VIEW VW_PRESTAMO AS
	SELECT IDPRESTAMO,IDLECTOR,NOEJEMPLAR,IDMATERIAL,FECHAPREST,
	FECHAVENC,DIASATRASO,FECHAMULTA,MONTO,FECHADEV,NUMREFRENDO
	,FECHAREFERENDO
    FROM PRESTAMO

--VIEW DE TESIS
CREATE OR REPLACE VIEW VW_TESIS AS
	SELECT IDMATERIAL,IDDIRECTOR,IDTESIS,CARRERA,ANOPUB
    FROM TESIS

--VIEW DE TIPOLECTOR
CREATE OR REPLACE VIEW VW_TIPOLECTOR AS
	SELECT TIPO,LIMITEMAT,DIASPREST,REFRENDOS
    FROM TIPOLECTOR