--********************************TRIGGERS**********************************
--TRIGGER PARA CAMBIAR EL ESTATUS AL INSERTAR EN PRESTAMO
CREATE OR REPLACE TRIGGER TR_ESTATUS_PRESTAMO
AFTER INSERT ON PRESTAMO
FOR EACH ROW
DECLARE
V_ESTATUS NUMBER;
BEGIN    
    V_ESTATUS := FT_PRESTAMODISP(:NEW.IDMATERIAL);
    IF(V_ESTATUS=1)
    THEN 
    	DBMS_OUTPUT.PUT_LINE('ERROR, EL MATERIAL NO PUEDE SER PRESTADO');
    ELSE
    	UPDATE ESTATUS SET 'PRESTAMO'
    	FROM EJEMPLAR
    	JOIN PRESTAMO ON (PRESTAMO.IDMATERIAL = EJEMPLAR.IDMATERIAL)
    	WHERE EJEMPLAR.IDMATERIAL = :NEW.IDMATERIAL;
    END IF;
END;
/