--FUNCION QUE CALCULA LA FECHA DE DEVOLUCION A PARTIR DE LA FECHA ACTUAL
--@IN NUMERO de identificacion del lector
--@OUT FECHA que representa la fecha de devolucion 
CREATE OR REPLACE FUNCTION FT_FECHADEV (IDLECT IN LECTOR.IDLECTOR%TYPE)
RETURN DATE
IS
vDiasPrest tipolector.diasprest%TYPE;
BEGIN
    SELECT diasprest
    INTO vDiasPrest
    FROM LECTOR  
    NATURAL JOIN TIPOLECTOR 
    WHERE idlector=IDLECT;
    RETURN (SYSDATE + vDiasprest);
END FT_FECHADEV;
    