SET SERVEROUTPUT ON
--*******************************FUNCIONES**********************************
--FUNCION PARA OBTENER SI UN LECTOR TIENE MULTA
CREATE OR REPLACE FUNCTION FT_MULTA (V_IDLECTOR CHAR)
RETURN NUMBER
IS
V_ADEUDO LECTOR.ADEUDO%TYPE;
V_MULTA NUMBER;
BEGIN
    SELECT ADEUDO
    INTO V_ADEUDO
    FROM LECTOR
    WHERE IDLECTOR = V_IDLECTOR; 
    IF (V_ADEUDO <> 0 OR V_ADEUDO <> NULL)
        THEN V_MULTA:=1;
    ELSE
        V_MULTA:=0;
    END IF;
    RETURN(V_MULTA);
END;
/
--FUNCION PARA OBTENER DISPONIBILIDAD DE MATERIAL POR SU ESTATUS
CREATE OR REPLACE FUNCTION FT_PRESTAMODISP (V_IDMATERIAL CHAR)
RETURN NUMBER
IS
V_ESTATUS EJEMPLAR.ESTATUS%TYPE;
BEGIN
    SELECT ESTATUS
    INTO V_ESTATUS
    FROM EJEMPLAR
    WHERE IDMATERIAL = V_IDMATERIAL;
    RETURN(V_ESTATUS);
END;
/
--FUNCION QUE CALCULA LA FECHA DE DEVOLUCION A PARTIR DE LA FECHA ACTUAL
--IN NUMERO de identificacion del lector
--OUT FECHA que representa la fecha de devolucion 
CREATE OR REPLACE FUNCTION FT_FECHADEV (IDLECT CHAR)
RETURN DATE
IS
VDIASPREST TIPOLECTOR.DIASPREST%TYPE;
VDATEDEV DATE;
BEGIN
    SELECT DIASPREST
    INTO VDIASPREST
    FROM LECTOR  
    NATURAL JOIN TIPOLECTOR 
    WHERE IDLECTOR=IDLECT;
    VDATEDEV:=SYSDATE+VDIASPREST;
    RETURN (VDATEDEV);
END FT_FECHADEV;
/
--FUNCION PARA LOS REFRENDOS
CREATE OR REPLACE FUNCTION FT_OBTIENE_REFRENDO(IDLECT CHAR)
RETURN NUMBER
IS
	VREFRENDO NUMBER(5);
	VTIPO VARCHAR2(12);
BEGIN
	SELECT TIPO INTO VTIPO
	FROM LECTOR
	WHERE IDLECTOR = IDLECT; 
	IF VTIPO = 'ESTUDIANTE' THEN
        SELECT DIASPREST 
        INTO VREFRENDO
        FROM TIPOLECTOR
        WHERE TIPO='ESTUDIANTE';
	END IF;
	IF VTIPO = 'PROFESOR' THEN
		SELECT DIASPREST 
        INTO VREFRENDO
        FROM TIPOLECTOR
        WHERE TIPO='PROFESOR';
	END IF;
	IF VTIPO = 'INVESTIGADOR' THEN
		SELECT DIASPREST 
        INTO VREFRENDO
        FROM TIPOLECTOR
        WHERE TIPO='INVESTIGADOR';
	END IF;
	RETURN (VREFRENDO);
END FT_OBTIENE_REFRENDO;
/
--FUNCION QUE DEVUELVE EL NUMERO DE REFRENDOS RESTANTES
CREATE OR REPLACE FUNCTION FT_ACTUALIZA_REFRENDO(IDLECT CHAR,NOEJEMPLAR NUMBER,IDMATERIAL CHAR)
RETURN NUMBER
IS
	VREFRENDOSRESTANTES NUMBER(5);
BEGIN
	SELECT NUMREFRENDO 
    INTO VREFRENDOSRESTANTES
	FROM PRESTAMO
	WHERE IDLECTOR = IDLECT 
	AND NOEJEMPLAR = NOEJEMPLAR
	AND IDMATERIAL = IDMATERIAL;
	VREFRENDOSRESTANTES:=VREFRENDOSRESTANTES - 1;
	RETURN (VREFRENDOSRESTANTES);
END FT_ACTUALIZA_REFRENDO;
/
DROP FUNCTION FT_PRESTAMODISP;
DROP FUNCTION FT_MULTA;
DROP FUNCTION FT_FECHADEV;
DROP FUNCTION FT_OBTIENE_REFRENDO;
DROP FUNCTION FT_ACTUALIZA_REFRENDO;
COMMIT;





