SET SERVEROUTPUT ON
--*******************************FUNCIONES**********************************
--FUNCION QUE CALCULA LA FECHA DE DEVOLUCION A PARTIR DE LA FECHA ACTUAL
--IN NUMERO de identificacion del lector
--OUT FECHA que representa la fecha de devolucion 
CREATE OR REPLACE FUNCTION FT_FECHADEV (IDLECT CHAR)
RETURN DATE
IS
VDIASPREST TIPOLECTOR.DIASPREST%TYPE;
VDATEDEV DATE;
BEGIN
    SELECT DIASPREST
    INTO VDIASPREST
    FROM LECTOR  
    NATURAL JOIN TIPOLECTOR 
    WHERE IDLECTOR=IDLECT;
    VDATEDEV:=SYSDATE+VDIASPREST;
    RETURN (VDATEDEV);
END FT_FECHADEV;
/
--FUNCION PARA LOS REFRENDOS
CREATE OR REPLACE FUNCTION FT_OBTIENE_REFRENDO(IDLECT CHAR)
RETURN NUMBER
IS
    VREFRENDO NUMBER(5);
    VTIPO VARCHAR2(12);
BEGIN
    SELECT TIPO 
    INTO VTIPO
    FROM LECTOR
    WHERE IDLECTOR = IDLECT; 
    IF VTIPO = 'ESTUDIANTE' THEN
        SELECT REFRENDOS 
        INTO VREFRENDO
        FROM TIPOLECTOR
        WHERE TIPO=VTIPO;
    END IF;
    IF VTIPO = 'PROFESOR' THEN
        SELECT REFRENDOS 
        INTO VREFRENDO
        FROM TIPOLECTOR
        WHERE TIPO=VTIPO;
    END IF;
    IF VTIPO = 'INVESTIGADOR' THEN
        SELECT REFRENDOS 
        INTO VREFRENDO
        FROM TIPOLECTOR
        WHERE TIPO=VTIPO;
    END IF;
    RETURN (VREFRENDO);
END FT_OBTIENE_REFRENDO;
/
--FUNCION QUE DEVUELVE EL NUMERO DE REFRENDOS RESTANTES
CREATE OR REPLACE FUNCTION FT_ACTUALIZA_REFRENDO(VIDLECT CHAR,VNOEJEMPLAR NUMBER,VIDMATERIAL CHAR)
RETURN NUMBER
IS
    VREFRENDOSRESTANTES NUMBER(5);
BEGIN
    SELECT NUMREFRENDO 
    INTO VREFRENDOSRESTANTES
    FROM PRESTAMO
    WHERE IDLECTOR = VIDLECT 
    AND NOEJEMPLAR = VNOEJEMPLAR
    AND IDMATERIAL = VIDMATERIAL;
    VREFRENDOSRESTANTES:=VREFRENDOSRESTANTES - 1;
    RETURN (VREFRENDOSRESTANTES);
END FT_ACTUALIZA_REFRENDO;
/
--FUNCION QUE CALCULA EL NUMERO DE MATERIALES QUE PUEDE SACAR
CREATE OR REPLACE FUNCTION FT_MATERIALRESTANTE(vIDLEC IN CHAR)
RETURN number
IS
vCantidad NUMBER;
vMax NUMBER;
VAUX NUMBER;
BEGIN
    SELECT count(*)  
    INTO vCantidad
    FROM prestamo
    WHERE IdLector=vIDLEC;
    SELECT limitemat
    INTO vMax
    FROM tipolector
    WHERE TIPO=(SELECT TIPO
                FROM LECTOR
                WHERE IdLector=vIDLEC);
    IF (vCantidad=0) THEN
        return(vmax);
    ELSE
        VAUX:=vmax-vCantidad;
        return(VAUX);
    END IF;
END FT_MATERIALRESTANTE;
/

--FUNCION QUE VERIFICA SI HAY MULTAS A CREAR
CREATE OR REPLACE FUNCTION ft_VERFICAMULTA(vIDLEC IN CHAR)
RETURN NUMBER
IS
VADEUDO NUMBER(5);
VNMULTAS NUMBER(1);
BEGIN
    SELECT ADEUDO
    INTO VADEUDO
    FROM LECTOR
    WHERE IDLECTOR=vIDLEC;
    VNMULTAS:=0;
    IF (VADEUDO<>0) THEN
        VNMULTAS:=1;
    END IF;
    RETURN (VNMULTAS);
END;
/

DROP FUNCTION FT_PRESTAMODISP;
DROP FUNCTION FT_MULTA;
DROP FUNCTION FT_FECHADEV;
DROP FUNCTION FT_OBTIENE_REFRENDO;
DROP FUNCTION FT_ACTUALIZA_REFRENDO;
DROP FUNCTION FT_MATERIALRESTANTE;
COMMIT;





